#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0
#  in conjunction with Tcl version 8.6
#    Jan 07, 2021 06:00:07 PM +0200  platform: Windows NT

import sys
sys.path.append('..')

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import AttendanceRep_support
from data import getUser,connect_to_db_and_collection

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    AttendanceRep_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    AttendanceRep_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def CheckCurrentAbs(self):
        mycol = connect_to_db_and_collection('EZSchooldb', 'Users')
        att=self.currentUser['attendance']
        self.Message1.configure(text=f'''{att} :כמות החיסורים המצטברת שלך הינה  ''')

    def __init__(self, top=None):
        self.currentUser=getUser()
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x182+383+106")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("דו''ח נוכחות")
        top.configure(background="#800040")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.4, rely=0.11, height=31, width=94)
        self.Label1.configure(background="#800040")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 12 -weight bold")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''דו''ח נוכחות''')

        self.Message1 = tk.Message(top)
        self.Message1.place(relx=0.55, rely=0.495, relheight=0.126
                , relwidth=0.417)
        self.Message1.configure(background="#800040")
        self.Message1.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(width=250)

        self.CheckCurrentAbs()

if __name__ == '__main__':
    vp_start_gui()





