#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0
#  in conjunction with Tcl version 8.6
#    Jan 01, 2021 04:15:37 PM +0200  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import classesReport_support
import Secretarymainmenu
import balanceReport1
import balanceReport2
import balanceReport3
import balanceReport4
import balanceReport5
import balanceReport6

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = classReport (root)
    classesReport_support.init(root, top)
    root.mainloop()

w = None
def create_class(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_class(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = classReport (w)
    classesReport_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_class():
    global w
    w.destroy()
    w = None

class classReport:
    def back(self):
        root.destroy()
        Secretarymainmenu.vp_start_gui()
    def openreport1(self):
        balanceReport1.vp_start_gui()

    def openreport2(self):
        balanceReport2.vp_start_gui()

    def openreport3(self):
        balanceReport3.vp_start_gui()

    def openreport4(self):
        balanceReport4.vp_start_gui()

    def openreport5(self):
        balanceReport5.vp_start_gui()
    def openreport6(self):
        balanceReport6.vp_start_gui()

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x443+380+151")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("פירוט יתרות")
        top.configure(background="#a8d3ff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.class1 = tk.Button(top)
        self.class1.place(relx=0.367, rely=0.133, height=44, width=137)
        self.class1.configure(activebackground="#ececec")
        self.class1.configure(activeforeground="#f9f2ff")
        self.class1.configure(background="#8080ff")
        self.class1.configure(cursor="hand2")
        self.class1.configure(disabledforeground="#a3a3a3")
        self.class1.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.class1.configure(foreground="#000000")
        self.class1.configure(highlightbackground="#d9d9d9")
        self.class1.configure(highlightcolor="black")
        self.class1.configure(pady="0")
        self.class1.configure(text='''כיתה א''')
        self.class1.configure(command=self.openreport1)


        self.class2 = tk.Button(top)
        self.class2.place(relx=0.367, rely=0.266, height=44, width=137)
        self.class2.configure(activebackground="#ececec")
        self.class2.configure(activeforeground="#000000")
        self.class2.configure(background="#8080ff")
        self.class2.configure(cursor="hand2")
        self.class2.configure(disabledforeground="#a3a3a3")
        self.class2.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.class2.configure(foreground="#000000")
        self.class2.configure(highlightbackground="#d9d9d9")
        self.class2.configure(highlightcolor="black")
        self.class2.configure(pady="0")
        self.class2.configure(text='''כיתה ב''')

        self.class3 = tk.Button(top)
        self.class3.place(relx=0.367, rely=0.4, height=44, width=137)
        self.class3.configure(activebackground="#ececec")
        self.class3.configure(activeforeground="#000000")
        self.class3.configure(background="#8080ff")
        self.class3.configure(cursor="hand2")
        self.class3.configure(disabledforeground="#a3a3a3")
        self.class3.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.class3.configure(foreground="#000000")
        self.class3.configure(highlightbackground="#d9d9d9")
        self.class3.configure(highlightcolor="black")
        self.class3.configure(pady="0")
        self.class3.configure(text='''כיתה ג''')

        self.class4 = tk.Button(top)
        self.class4.place(relx=0.367, rely=0.533, height=44, width=137)
        self.class4.configure(activebackground="#ececec")
        self.class4.configure(activeforeground="#000000")
        self.class4.configure(background="#8080ff")
        self.class4.configure(cursor="hand2")
        self.class4.configure(disabledforeground="#a3a3a3")
        self.class4.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.class4.configure(foreground="#000000")
        self.class4.configure(highlightbackground="#d9d9d9")
        self.class4.configure(highlightcolor="black")
        self.class4.configure(pady="0")
        self.class4.configure(text='''כיתה ד''')

        self.class5 = tk.Button(top)
        self.class5.place(relx=0.367, rely=0.666, height=44, width=137)
        self.class5.configure(activebackground="#ececec")
        self.class5.configure(activeforeground="#000000")
        self.class5.configure(background="#8080ff")
        self.class5.configure(cursor="hand2")
        self.class5.configure(disabledforeground="#a3a3a3")
        self.class5.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.class5.configure(foreground="#000000")
        self.class5.configure(highlightbackground="#d9d9d9")
        self.class5.configure(highlightcolor="black")
        self.class5.configure(pady="0")
        self.class5.configure(text='''כיתה ה''')

        self.class6 = tk.Button(top)
        self.class6.place(relx=0.367, rely=0.799, height=44, width=137)
        self.class6.configure(activebackground="#ececec")
        self.class6.configure(activeforeground="#000000")
        self.class6.configure(background="#8080ff")
        self.class6.configure(cursor="hand2")
        self.class6.configure(disabledforeground="#a3a3a3")
        self.class6.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.class6.configure(foreground="#000000")
        self.class6.configure(highlightbackground="#d9d9d9")
        self.class6.configure(highlightcolor="black")
        self.class6.configure(pady="0")
        self.class6.configure(text='''כיתה ו''')

        self.mainmenu = tk.Button(top)
        self.mainmenu.place(relx=0.067, rely=0.867, height=44, width=117)
        self.mainmenu.configure(activebackground="#ececec")
        self.mainmenu.configure(activeforeground="#000000")
        self.mainmenu.configure(background="#8080ff")
        self.mainmenu.configure(cursor="hand2")
        self.mainmenu.configure(disabledforeground="#a3a3a3")
        self.mainmenu.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.mainmenu.configure(foreground="#000000")
        self.mainmenu.configure(highlightbackground="#d9d9d9")
        self.mainmenu.configure(highlightcolor="black")
        self.mainmenu.configure(pady="0")
        self.mainmenu.configure(text='''תפריט ראשי''')
        self.mainmenu.configure(command=self.back)

        self.class2.configure(command=self.openreport2)
        self.class3.configure(command=self.openreport3)
        self.class4.configure(command=self.openreport4)
        self.class5.configure(command=self.openreport5)
        self.class6.configure(command=self.openreport6)


        self.Message1 = tk.Message(top)
        self.Message1.place(relx=0.05, rely=0.023, relheight=0.072
                , relwidth=0.85)
        self.Message1.configure(background="#a8d3ff")
        self.Message1.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''נא לבחור כיתה על מנת לצפות בפירוט היתרות''')
        self.Message1.configure(width=510)

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#ececec")
        Popupmenu1.configure(activeborderwidth="1")
        Popupmenu1.configure(activeforeground="#000000")
        Popupmenu1.configure(background="#d9d9d9")
        Popupmenu1.configure(borderwidth="1")
        Popupmenu1.configure(disabledforeground="#a3a3a3")
        Popupmenu1.configure(foreground="#000000")
        Popupmenu1.post(event.x_root, event.y_root)

if __name__ == '__main__':
    vp_start_gui()





