#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0
#  in conjunction with Tcl version 8.6
#    Jan 07, 2021 08:03:17 AM +0200  platform: Windows NT

import sys
import pymongo
sys.path.append('..')

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import InventReport_support
from data import getUser, connect_to_db_and_collection

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = InventReport (root)
    InventReport_support.init(root, top)
    root.mainloop()

w = None
def create_InventReport(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_InventReport(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = InventReport (w)
    InventReport_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_InventReport():
    global w
    w.destroy()
    w = None

class InventReport:
    def InsertInvent(self):
        mycol = connect_to_db_and_collection('EZSchooldb','Inventory')
        for item in mycol.find({}):
            self.InventTree.insert('', 'end',text=item['id'],values=(item['item_name'],item['units_available'],item['price']))

    def __init__(self, top=None):
        self.current_user = getUser()


        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+633+236")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("דוח מלאי")
        top.configure(background="#80ffff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.IdL = tk.Label(top)
        self.IdL.place(relx=0.35, rely=0.1, height=41, width=214)
        self.IdL.configure(activebackground="#f9f9f9")
        self.IdL.configure(activeforeground="black")
        self.IdL.configure(background="#00ff40")
        self.IdL.configure(disabledforeground="#a3a3a3")
        self.IdL.configure(font="-family {Segoe UI} -size 14 -weight bold -underline 1")
        self.IdL.configure(foreground="#000000")
        self.IdL.configure(highlightbackground="#d9d9d9")
        self.IdL.configure(highlightcolor="black")
        self.IdL.configure(relief="ridge")
        self.IdL.configure(text=f'''דו"ח מלאי''')

        self.InventTree = ttk.Treeview(top)
        self.InventTree["columns"] = ("one", "two","three")
        self.InventTree.column("#0", width=100, minwidth=100, stretch=tk.NO)
        self.InventTree.column("one", width=150, minwidth=100, stretch=tk.NO)
        self.InventTree.column("two", width=150, minwidth=150, stretch=tk.NO)
        self.InventTree.column("three", width=100, minwidth=100, stretch=tk.NO)
        self.InventTree.heading("#0", text='מק"ט', anchor=tk.W)
        self.InventTree.heading("one", text="שם המוצר", anchor=tk.W)
        self.InventTree.heading("two", text="כמות", anchor=tk.W)
        self.InventTree.heading("three", text="מחיר", anchor=tk.W)
        self.InventTree.place(relx=0.085, rely=0.4)

        self.InsertInvent()

if __name__ == '__main__':
    vp_start_gui()





