#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0
#  in conjunction with Tcl version 8.6
#    Dec 19, 2020 06:29:24 PM +0200  platform: Windows NT

import sys
import pymongo

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import InventoryManagment_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = InventManage (root)
    InventoryManagment_support.init(root, top)
    root.mainloop()

w = None
def create_InventManage(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_InventManage(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = InventManage (w)
    InventoryManagment_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_InventManage():
    global w
    w.destroy()
    w = None

class InventManage:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1550x900+50+32")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("Inventory Managment")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.style.configure('Treeview',  font="TkDefaultFont")
        self.InventoryManage = ScrolledTreeView(top)
        self.InventoryManage.place(relx=0.026, rely=0.6, relheight=0.386
                , relwidth=0.935)
        self.InventoryManage.configure(columns="Col1 Col2 Col3")
        # build_treeview_support starting.
        self.InventoryManage.heading("#0",text="Item ID")
        self.InventoryManage.heading("#0",anchor="center")
        self.InventoryManage.column("#0",width="256")
        self.InventoryManage.column("#0",minwidth="2")
        self.InventoryManage.column("#0",stretch="1")
        self.InventoryManage.column("#0",anchor="w")
        self.InventoryManage.heading("Col1",text="Name")
        self.InventoryManage.heading("Col1",anchor="center")
        self.InventoryManage.column("Col1",width="658")
        self.InventoryManage.column("Col1",minwidth="2")
        self.InventoryManage.column("Col1",stretch="1")
        self.InventoryManage.column("Col1",anchor="w")
        self.InventoryManage.heading("Col2",text="Units")
        self.InventoryManage.heading("Col2",anchor="center")
        self.InventoryManage.column("Col2",width="259")
        self.InventoryManage.column("Col2",minwidth="2")
        self.InventoryManage.column("Col2",stretch="1")
        self.InventoryManage.column("Col2",anchor="w")
        self.InventoryManage.heading("Col3",text="Price")
        self.InventoryManage.heading("Col3",anchor="center")
        self.InventoryManage.column("Col3",width="258")
        self.InventoryManage.column("Col3",minwidth="20")
        self.InventoryManage.column("Col3",stretch="1")
        self.InventoryManage.column("Col3",anchor="w")

        self.UntUpbtn = tk.Button(top)
        self.UntUpbtn.place(relx=0.032, rely=0.144, height=64, width=97)
        self.UntUpbtn.configure(activebackground="#ececec")
        self.UntUpbtn.configure(activeforeground="#000000")
        self.UntUpbtn.configure(background="#d9d9d9")
        self.UntUpbtn.configure(disabledforeground="#a3a3a3")
        self.UntUpbtn.configure(foreground="#000000")
        self.UntUpbtn.configure(highlightbackground="#d9d9d9")
        self.UntUpbtn.configure(highlightcolor="black")
        self.UntUpbtn.configure(pady="0")
        self.UntUpbtn.configure(text='''עדכון כמות''')

        self.PrcUpbtn = tk.Button(top)
        self.PrcUpbtn.place(relx=0.032, rely=0.256, height=64, width=97)
        self.PrcUpbtn.configure(activebackground="#ececec")
        self.PrcUpbtn.configure(activeforeground="#000000")
        self.PrcUpbtn.configure(background="#d9d9d9")
        self.PrcUpbtn.configure(disabledforeground="#a3a3a3")
        self.PrcUpbtn.configure(foreground="#000000")
        self.PrcUpbtn.configure(highlightbackground="#d9d9d9")
        self.PrcUpbtn.configure(highlightcolor="black")
        self.PrcUpbtn.configure(pady="0")
        self.PrcUpbtn.configure(text='''עדכון מחיר''')

        self.UnitEntry = tk.Entry(top)
        self.UnitEntry.place(relx=0.11, rely=0.178, height=30, relwidth=0.138)
        self.UnitEntry.configure(background="white")
        self.UnitEntry.configure(disabledforeground="#a3a3a3")
        self.UnitEntry.configure(font="TkFixedFont")
        self.UnitEntry.configure(foreground="#000000")
        self.UnitEntry.configure(insertbackground="black")

        self.priceEntry = tk.Entry(top)
        self.priceEntry.place(relx=0.11, rely=0.289, height=30, relwidth=0.138)
        self.priceEntry.configure(background="white")
        self.priceEntry.configure(disabledforeground="#a3a3a3")
        self.priceEntry.configure(font="TkFixedFont")
        self.priceEntry.configure(foreground="#000000")
        self.priceEntry.configure(insertbackground="black")

        self.backbtn = tk.Button(top)
        self.backbtn.place(relx=0.865, rely=0.033, height=74, width=157)
        self.backbtn.configure(activebackground="#ececec")
        self.backbtn.configure(activeforeground="#000000")
        self.backbtn.configure(background="#d9d9d9")
        self.backbtn.configure(disabledforeground="#a3a3a3")
        self.backbtn.configure(foreground="#000000")
        self.backbtn.configure(highlightbackground="#d9d9d9")
        self.backbtn.configure(highlightcolor="black")
        self.backbtn.configure(pady="0")
        self.backbtn.configure(text='''אחורה''')

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''
    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))
        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')
        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)
        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                  + tk.Place.__dict__.keys()
        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledTreeView(AutoScroll, ttk.Treeview):
    '''A standard ttk Treeview widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        ttk.Treeview.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')

if __name__ == '__main__':
    vp_start_gui()





