#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Jan 07, 2021 11:49:09 PM +0200  platform: Windows NT

import sys
sys.path.append("..")

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Payment_Shop_Secretary_support
import Secretarymainmenu
import Payment_Shop_Student_support
from data import connect_to_db_and_collection, getUser, GetChosenUser
import Studentmainmenu
from tkinter import messagebox
import datetime

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = shop_payment (root)
    Payment_Shop_Secretary_support.init(root, top)
    root.mainloop()

w = None
def create_shop_payment(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_shop_payment(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = shop_payment (w)
    Payment_Shop_Secretary_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_shop_payment():
    global w
    w.destroy()
    w = None

class shop_payment:
    def back(self):
        root.destroy()
        Secretarymainmenu.vp_start_gui()


    def user_details(self):
        return f'''{self.currentUser['name']}\n{self.currentUser['id']}'''

    def get_total_price(self):
        return f'''{self.currentUser['cart']['total price']}₪'''

    def submit(self):
        inventory_collec = connect_to_db_and_collection('EZSchooldb', 'Inventory')
        users_collect=connect_to_db_and_collection('EZSchooldb','Users')
        year=int(self.year_entry.get())
        month=int(self.month_entry.get())
        idofcard=self.id_entry.get()
        cardnumber=self.card_entry.get()
        flag=1
        if flag:
            if(len(cardnumber)<16):
                tk.messagebox.showwarning('Shop', 'מספר הכרטיס אינו תקין-קצר מידי, נסה שוב')
                flag=0
        if flag:
            for c in cardnumber:
                if c<'0'or c>'9':
                    flag=0
                    tk.messagebox.showwarning('Shop', 'מספר הכרטיס אינו תקין-חייב להכיל ספרות בלבד, נסה שוב')

        if flag:
            if len(idofcard) != 9:
                tk.messagebox.showwarning('Shop', 'מספר תעודת הזהות אינו תקין-אורכו צריך להיות 9 ספרות, נסה שוב')
                flag = 0
        if flag:
            for c in idofcard:
                if c < '0' or c > '9':
                    flag = 0
                    tk.messagebox.showwarning('Shop', 'מספר תעודת הזהות אינו תקין-חייב להכיל ספרות בלבד, נסה שוב')

        today=datetime.datetime.today()
        yeartoday=today.year
        monthtoday=today.month
        if flag:
            if month <1 or month>12:
                print(month)
                tk.messagebox.showwarning('Shop', 'תאריך לא תקין')
                flag = 0

        if flag:
            if year<yeartoday:
                tk.messagebox.showwarning('Shop', 'תאריך לא תקין, נסה שוב')
                flag = 0
            elif year==yeartoday:
                if month<monthtoday:
                    tk.messagebox.showwarning('Shop', 'תאריך לא תקין')
                    flag = 0


        if flag:
            for item in inventory_collec.find({}):
                inventory_collec.update_one({'item_name': item['item_name']},
                                            {'$set':{'units_available':item['units_available']-
                                                                       self.currentUser['cart'][item['item_name']]}})

            cart_list = self.currentUser['cart']
            if not 'receipts' in self.currentUser.keys():
                self.currentUser['receipts'] = []
            cart_list['receipt_number'] = len(self.currentUser['receipts'])
            if cart_list['receipt_number']==None:
                cart_list['receipt_number']=1
            else:
                cart_list['receipt_number'] = cart_list['receipt_number'] + 1
            receipts = self.currentUser['receipts']
            cart_list['purchase_time'] = today
            receipts.append(cart_list)
            users_collect.update_one({'id':self.currentUser['id']},{'$set':{'receipts':receipts}})
            users_collect.update_one({'id':self.currentUser['id']},{'$unset': {'cart':1}})
            tk.messagebox._show('Shop', 'התשלום התקבל בהצלחה, הפריטים ישלחו אל התלמיד בקרוב')
            self.back()


    def __init__(self, top=None):
        self.currentUser = GetChosenUser()
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("763x638+693+172")
        top.minsize(148, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("תשלום חנות")
        top.configure(background="#c9e9e8")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.mainmenu = tk.Button(top)
        self.mainmenu.place(relx=0.05, rely=0.843, height=44, width=147)
        self.mainmenu.configure(activebackground="#ececec")
        self.mainmenu.configure(activeforeground="#000000")
        self.mainmenu.configure(background="#8fd1cf")
        self.mainmenu.configure(disabledforeground="#a3a3a3")
        self.mainmenu.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.mainmenu.configure(foreground="#000000")
        self.mainmenu.configure(highlightbackground="#d9d9d9")
        self.mainmenu.configure(highlightcolor="black")
        self.mainmenu.configure(pady="0")
        self.mainmenu.configure(text='''תפריט ראשי''')
        self.mainmenu.configure(command=self.back)

        self.submitpayment = tk.Button(top)
        self.submitpayment.place(relx=0.35, rely=0.843, height=44, width=137)
        self.submitpayment.configure(activebackground="#ececec")
        self.submitpayment.configure(activeforeground="#000000")
        self.submitpayment.configure(background="#8fd1cf")
        self.submitpayment.configure(disabledforeground="#a3a3a3")
        self.submitpayment.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.submitpayment.configure(foreground="#000000")
        self.submitpayment.configure(highlightbackground="#d9d9d9")
        self.submitpayment.configure(highlightcolor="black")
        self.submitpayment.configure(pady="0")
        self.submitpayment.configure(text='''תשלום''')
        self.submitpayment.configure(command=self.submit)

        self.card_entry = tk.Entry(top)
        self.card_entry.place(relx=0.341, rely=0.313, height=30, relwidth=0.294)
        self.card_entry.configure(background="white")
        self.card_entry.configure(disabledforeground="#a3a3a3")
        self.card_entry.configure(font="TkFixedFont")
        self.card_entry.configure(foreground="#000000")
        self.card_entry.configure(highlightbackground="#d9d9d9")
        self.card_entry.configure(highlightcolor="black")
        self.card_entry.configure(insertbackground="black")
        self.card_entry.configure(selectbackground="blue")
        self.card_entry.configure(selectforeground="white")

        self.id_entry = tk.Entry(top)
        self.id_entry.place(relx=0.433, rely=0.392, height=30, relwidth=0.189)
        self.id_entry.configure(background="white")
        self.id_entry.configure(disabledforeground="#a3a3a3")
        self.id_entry.configure(font="TkFixedFont")
        self.id_entry.configure(foreground="#000000")
        self.id_entry.configure(highlightbackground="#d9d9d9")
        self.id_entry.configure(highlightcolor="black")
        self.id_entry.configure(insertbackground="black")
        self.id_entry.configure(selectbackground="blue")
        self.id_entry.configure(selectforeground="white")

        self.userDetails = tk.Message(top)
        self.userDetails.place(relx=0.233, rely=0.022, relheight=0.118
                , relwidth=0.617)
        self.userDetails.configure(background="#c9e9e8")
        self.userDetails.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.userDetails.configure(foreground="#000000")
        self.userDetails.configure(highlightbackground="#d9d9d9")
        self.userDetails.configure(highlightcolor="black")
        self.userDetails.configure(text=self.user_details())
        self.userDetails.configure(width=370)

        self.amount = tk.Message(top)
        self.amount.place(relx=0.633, rely=0.223, relheight=0.05, relwidth=0.233)

        self.amount.configure(background="#c9e9e8")
        self.amount.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.amount.configure(foreground="#000000")
        self.amount.configure(highlightbackground="#d9d9d9")
        self.amount.configure(highlightcolor="black")
        self.amount.configure(text='''סכום לתשלום''')
        self.amount.configure(width=140)

        self.card = tk.Message(top)
        self.card.place(relx=0.65, rely=0.31, relheight=0.052, relwidth=0.218)
        self.card.configure(background="#c9e9e8")
        self.card.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.card.configure(foreground="#000000")
        self.card.configure(highlightbackground="#d9d9d9")
        self.card.configure(highlightcolor="black")
        self.card.configure(text='''מספר כרטיס''')
        self.card.configure(width=130)

        self.id = tk.Message(top)
        self.id.place(relx=0.683, rely=0.4, relheight=0.052, relwidth=0.25)
        self.id.configure(background="#c9e9e8")
        self.id.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.id.configure(foreground="#000000")
        self.id.configure(highlightbackground="#d9d9d9")
        self.id.configure(highlightcolor="black")
        self.id.configure(text='''תעודת זהות של בעל כרטיס''')
        self.id.configure(width=150)

        self.year = tk.Message(top)
        self.year.place(relx=0.617, rely=0.489, relheight=0.052, relwidth=0.233)
        self.year.configure(background="#c9e9e8")
        self.year.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.year.configure(foreground="#000000")
        self.year.configure(highlightbackground="#d9d9d9")
        self.year.configure(highlightcolor="black")
        self.year.configure(text='''שנה''')
        self.year.configure(width=140)

        self.month = tk.Message(top)
        self.month.place(relx=0.683, rely=0.578, relheight=0.05, relwidth=0.1)
        self.month.configure(background="#c9e9e8")
        self.month.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.month.configure(foreground="#000000")
        self.month.configure(highlightbackground="#d9d9d9")
        self.month.configure(highlightcolor="black")
        self.month.configure(text='''חודש''')
        self.month.configure(width=60)

        self.year_entry = tk.Entry(top)
        self.year_entry.place(relx=0.511, rely=0.486, height=30, relwidth=0.11)
        self.year_entry.configure(background="white")
        self.year_entry.configure(disabledforeground="#a3a3a3")
        self.year_entry.configure(font="TkFixedFont")
        self.year_entry.configure(foreground="#000000")
        self.year_entry.configure(highlightbackground="#d9d9d9")
        self.year_entry.configure(highlightcolor="black")
        self.year_entry.configure(insertbackground="black")
        self.year_entry.configure(selectbackground="blue")
        self.year_entry.configure(selectforeground="white")

        self.month_entry = tk.Entry(top)
        self.month_entry.place(relx=0.524, rely=0.58, height=30, relwidth=0.11)
        self.month_entry.configure(background="white")
        self.month_entry.configure(disabledforeground="#a3a3a3")
        self.month_entry.configure(font="TkFixedFont")
        self.month_entry.configure(foreground="#000000")
        self.month_entry.configure(highlightbackground="#d9d9d9")
        self.month_entry.configure(highlightcolor="black")
        self.month_entry.configure(insertbackground="black")
        self.month_entry.configure(selectbackground="blue")
        self.month_entry.configure(selectforeground="white")

        self.total_cost = tk.Message(top)
        self.total_cost.place(relx=0.498, rely=0.204, relheight=0.082
                , relwidth=0.127)
        self.total_cost.configure(background="#c9e9e8")
        self.total_cost.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.total_cost.configure(foreground="#000000")
        self.total_cost.configure(highlightbackground="#d9d9d9")
        self.total_cost.configure(highlightcolor="black")
        self.total_cost.configure(text=self.get_total_price())
        self.total_cost.configure(width=97)

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#ececec")
        Popupmenu1.configure(activeborderwidth="1")
        Popupmenu1.configure(activeforeground="#000000")
        Popupmenu1.configure(background="#d9d9d9")
        Popupmenu1.configure(borderwidth="1")
        Popupmenu1.configure(disabledforeground="#a3a3a3")
        Popupmenu1.configure(foreground="#000000")
        Popupmenu1.post(event.x_root, event.y_root)

if __name__ == '__main__':
    vp_start_gui()





