#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0
#  in conjunction with Tcl version 8.6
#    Dec 31, 2020 04:54:20 PM +0200  platform: Windows NT

import sys
sys.path.append('..')

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import SekerRes_support
from data import seker_db_init

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    SekerRes_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    SekerRes_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def SekerOutcomes(self):
        myCol = seker_db_init()
        data = myCol.find({})
        Q1, Q2, Q3, Q4, Q5, Q6, Q7, Q8 = {'1': 0, '2': 0, '3': 0}, {'1': 0, '2': 0, '3': 0}, {'1': 0, '2': 0, '3': 0}, {
            '1': 0, '2': 0, '3': 0}, \
                                         {'1': 0, '2': 0, '3': 0}, {'1': 0, '2': 0, '3': 0}, {'1': 0, '2': 0, '3': 0}, {
                                             '1': 0, '2': 0, '3': 0}
        counter=0
        for oneSeker in data:
            if oneSeker['q1'] == '1':
                Q1['1'] += 1
            elif oneSeker['q1'] == '2':
                Q1['2'] += 1
            elif oneSeker['q1'] == '3':
                Q1['3'] += 1
            if oneSeker['q2'] == '1':
                Q2['1'] += 1
            elif oneSeker['q2'] == '2':
                Q2['2'] += 1
            elif oneSeker['q2'] == '3':
                Q2['3'] += 1
            if oneSeker['q3'] == '1':
                Q3['1'] += 1
            elif oneSeker['q3'] == '2':
                Q3['2'] += 1
            elif oneSeker['q3'] == '3':
                Q3['3'] += 1
            if oneSeker['q4'] == '1':
                Q4['1'] += 1
            elif oneSeker['q4'] == '2':
                Q4['2'] += 1
            elif oneSeker['q4'] == '3':
                Q4['3'] += 1
            if oneSeker['q5'] == '1':
                Q5['1'] += 1
            elif oneSeker['q5'] == '2':
                Q5['2'] += 1
            elif oneSeker['q5'] == '3':
                Q5['3'] += 1
            if oneSeker['q6'] == '1':
                Q6['1'] += 1
            elif oneSeker['q6'] == '2':
                Q6['2'] += 1
            elif oneSeker['q6'] == '3':
                Q6['3'] += 1
            if oneSeker['q7'] == '1':
                Q7['1'] += 1
            elif oneSeker['q7'] == '2':
                Q7['2'] += 1
            elif oneSeker['q7'] == '3':
                Q7['3'] += 1
            if oneSeker['q8'] == '1':
                Q8['1'] += 1
            elif oneSeker['q8'] == '2':
                Q8['2'] += 1
            elif oneSeker['q8'] == '3':
                Q8['3'] += 1
            counter += 1
        self.q11.configure(text=f'''{Q1['1']}''')
        self.q12.configure(text=f'''{Q1['2']}''')
        self.q13.configure(text=f'''{Q1['3']}''')
        self.q21.configure(text=f'''{Q2['1']}''')
        self.q22.configure(text=f'''{Q2['2']}''')
        self.q23.configure(text=f'''{Q2['3']}''')
        self.q31.configure(text=f'''{Q3['1']}''')
        self.q32.configure(text=f'''{Q3['2']}''')
        self.q33.configure(text=f'''{Q3['3']}''')
        self.q41.configure(text=f'''{Q4['1']}''')
        self.q42.configure(text=f'''{Q4['2']}''')
        self.q43.configure(text=f'''{Q4['3']}''')
        self.q51.configure(text=f'''{Q5['1']}''')
        self.q52.configure(text=f'''{Q5['2']}''')
        self.q53.configure(text=f'''{Q5['3']}''')
        self.q61.configure(text=f'''{Q6['1']}''')
        self.q62.configure(text=f'''{Q6['2']}''')
        self.q63.configure(text=f'''{Q6['3']}''')
        self.q71.configure(text=f'''{Q7['1']}''')
        self.q72.configure(text=f'''{Q7['2']}''')
        self.q73.configure(text=f'''{Q7['3']}''')
        self.q81.configure(text=f'''{Q8['1']}''')
        self.q82.configure(text=f'''{Q8['2']}''')
        self.q83.configure(text=f'''{Q8['3']}''')
        self.Allpar.configure(text=f'''בסקר השתתפו   {counter}   תלמידים''')
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1366x705+383+106")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("תוצאות סקר")
        top.configure(background="#8080ff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.4, rely=0.067, height=64, width=283)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#8080ff")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 12 -weight bold")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''תוצאות סקר''')

        self.Allpar = tk.Label(top)
        self.Allpar.place(relx=0.366, rely=0.156, height=33, width=738)
        self.Allpar.configure(activebackground="#f9f9f9")
        self.Allpar.configure(activeforeground="black")
        self.Allpar.configure(background="#8080ff")
        self.Allpar.configure(disabledforeground="#a3a3a3")
        self.Allpar.configure(font="-family {Segoe UI} -size 12")
        self.Allpar.configure(foreground="#000000")
        self.Allpar.configure(highlightbackground="#d9d9d9")
        self.Allpar.configure(highlightcolor="black")

        self.Q1 = tk.Label(top)
        self.Q1.place(relx=0.659, rely=0.27, height=33, width=120)
        self.Q1.configure(activebackground="#f9f9f9")
        self.Q1.configure(activeforeground="black")
        self.Q1.configure(background="#8080ff")
        self.Q1.configure(disabledforeground="#a3a3a3")
        self.Q1.configure(font="-family {Segoe UI} -size 12")
        self.Q1.configure(foreground="#000000")
        self.Q1.configure(highlightbackground="#d9d9d9")
        self.Q1.configure(highlightcolor="black")
        self.Q1.configure(text='''בשאלה 1 הצביעו''')

        self.Q2 = tk.Label(top)
        self.Q2.place(relx=0.652, rely=0.34, height=22, width=143)
        self.Q2.configure(activebackground="#f9f9f9")
        self.Q2.configure(activeforeground="black")
        self.Q2.configure(background="#8080ff")
        self.Q2.configure(disabledforeground="#a3a3a3")
        self.Q2.configure(font="-family {Segoe UI} -size 12")
        self.Q2.configure(foreground="#000000")
        self.Q2.configure(highlightbackground="#d9d9d9")
        self.Q2.configure(highlightcolor="black")
        self.Q2.configure(text='''בשאלה 2 הצביעו''')

        self.Q3 = tk.Label(top)
        self.Q3.place(relx=0.659, rely=0.411, height=21, width=125)
        self.Q3.configure(activebackground="#f9f9f9")
        self.Q3.configure(activeforeground="black")
        self.Q3.configure(background="#8080ff")
        self.Q3.configure(disabledforeground="#a3a3a3")
        self.Q3.configure(font="-family {Segoe UI} -size 12")
        self.Q3.configure(foreground="#000000")
        self.Q3.configure(highlightbackground="#d9d9d9")
        self.Q3.configure(highlightcolor="black")
        self.Q3.configure(text='''בשאלה 3 הצביעו''')

        self.Q4 = tk.Label(top)
        self.Q4.place(relx=0.659, rely=0.482, height=21, width=126)
        self.Q4.configure(activebackground="#f9f9f9")
        self.Q4.configure(activeforeground="black")
        self.Q4.configure(background="#8080ff")
        self.Q4.configure(disabledforeground="#a3a3a3")
        self.Q4.configure(font="-family {Segoe UI} -size 12")
        self.Q4.configure(foreground="#000000")
        self.Q4.configure(highlightbackground="#d9d9d9")
        self.Q4.configure(highlightcolor="black")
        self.Q4.configure(text='''בשאלה 4 הצביעו''')

        self.Q5 = tk.Label(top)
        self.Q5.place(relx=0.652, rely=0.553, height=21, width=143)
        self.Q5.configure(activebackground="#f9f9f9")
        self.Q5.configure(activeforeground="black")
        self.Q5.configure(background="#8080ff")
        self.Q5.configure(disabledforeground="#a3a3a3")
        self.Q5.configure(font="-family {Segoe UI} -size 12")
        self.Q5.configure(foreground="#000000")
        self.Q5.configure(highlightbackground="#d9d9d9")
        self.Q5.configure(highlightcolor="black")
        self.Q5.configure(text='''בשאלה 5 הצביעו''')

        self.Q6 = tk.Label(top)
        self.Q6.place(relx=0.659, rely=0.61, height=21, width=126)
        self.Q6.configure(activebackground="#f9f9f9")
        self.Q6.configure(activeforeground="black")
        self.Q6.configure(background="#8080ff")
        self.Q6.configure(disabledforeground="#a3a3a3")
        self.Q6.configure(font="-family {Segoe UI} -size 12")
        self.Q6.configure(foreground="#000000")
        self.Q6.configure(highlightbackground="#d9d9d9")
        self.Q6.configure(highlightcolor="black")
        self.Q6.configure(text='''בשאלה 6 הצביעו''')

        self.Q7 = tk.Label(top)
        self.Q7.place(relx=0.659, rely=0.667, height=21, width=126)
        self.Q7.configure(activebackground="#f9f9f9")
        self.Q7.configure(activeforeground="black")
        self.Q7.configure(background="#8080ff")
        self.Q7.configure(disabledforeground="#a3a3a3")
        self.Q7.configure(font="-family {Segoe UI} -size 12")
        self.Q7.configure(foreground="#000000")
        self.Q7.configure(highlightbackground="#d9d9d9")
        self.Q7.configure(highlightcolor="black")
        self.Q7.configure(text='''בשאלה 7 הצביעו''')

        self.Q8 = tk.Label(top)
        self.Q8.place(relx=0.659, rely=0.723, height=21, width=126)
        self.Q8.configure(activebackground="#f9f9f9")
        self.Q8.configure(activeforeground="black")
        self.Q8.configure(background="#8080ff")
        self.Q8.configure(disabledforeground="#a3a3a3")
        self.Q8.configure(font="-family {Segoe UI} -size 12")
        self.Q8.configure(foreground="#000000")
        self.Q8.configure(highlightbackground="#d9d9d9")
        self.Q8.configure(highlightcolor="black")
        self.Q8.configure(text='''בשאלה 8 הצביעו''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.564, rely=0.227, height=21, width=36)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#8080ff")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Segoe UI} -size 12 -weight bold")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''1''')

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.483, rely=0.227, height=21, width=35)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#8080ff")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font="-family {Segoe UI} -size 12 -weight bold")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''2''')

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.41, rely=0.227, height=22, width=34)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#8080ff")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font="-family {Segoe UI} -size 12 -weight bold")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''3''')

        self.q11 = tk.Label(top)
        self.q11.place(relx=0.564, rely=0.284, height=21, width=36)
        self.q11.configure(activebackground="#f9f9f9")
        self.q11.configure(activeforeground="black")
        self.q11.configure(background="#d9d9d9")
        self.q11.configure(disabledforeground="#a3a3a3")
        self.q11.configure(foreground="#000000")
        self.q11.configure(highlightbackground="#d9d9d9")
        self.q11.configure(highlightcolor="black")

        self.q12 = tk.Label(top)
        self.q12.place(relx=0.483, rely=0.284, height=21, width=34)
        self.q12.configure(activebackground="#f9f9f9")
        self.q12.configure(activeforeground="black")
        self.q12.configure(background="#d9d9d9")
        self.q12.configure(disabledforeground="#a3a3a3")
        self.q12.configure(foreground="#000000")
        self.q12.configure(highlightbackground="#d9d9d9")
        self.q12.configure(highlightcolor="black")

        self.q13 = tk.Label(top)
        self.q13.place(relx=0.41, rely=0.284, height=21, width=34)
        self.q13.configure(activebackground="#f9f9f9")
        self.q13.configure(activeforeground="black")
        self.q13.configure(background="#d9d9d9")
        self.q13.configure(disabledforeground="#a3a3a3")
        self.q13.configure(foreground="#000000")
        self.q13.configure(highlightbackground="#d9d9d9")
        self.q13.configure(highlightcolor="black")

        self.q23 = tk.Label(top)
        self.q23.place(relx=0.41, rely=0.34, height=21, width=34)
        self.q23.configure(activebackground="#f9f9f9")
        self.q23.configure(activeforeground="black")
        self.q23.configure(background="#d9d9d9")
        self.q23.configure(disabledforeground="#a3a3a3")
        self.q23.configure(foreground="#000000")
        self.q23.configure(highlightbackground="#d9d9d9")
        self.q23.configure(highlightcolor="black")

        self.q22 = tk.Label(top)
        self.q22.place(relx=0.483, rely=0.34, height=21, width=34)
        self.q22.configure(activebackground="#f9f9f9")
        self.q22.configure(activeforeground="black")
        self.q22.configure(background="#d9d9d9")
        self.q22.configure(disabledforeground="#a3a3a3")
        self.q22.configure(foreground="#000000")
        self.q22.configure(highlightbackground="#d9d9d9")
        self.q22.configure(highlightcolor="black")

        self.q21 = tk.Label(top)
        self.q21.place(relx=0.564, rely=0.34, height=21, width=35)
        self.q21.configure(activebackground="#f9f9f9")
        self.q21.configure(activeforeground="black")
        self.q21.configure(background="#d9d9d9")
        self.q21.configure(disabledforeground="#a3a3a3")
        self.q21.configure(foreground="#000000")
        self.q21.configure(highlightbackground="#d9d9d9")
        self.q21.configure(highlightcolor="black")

        self.q33 = tk.Label(top)
        self.q33.place(relx=0.41, rely=0.397, height=21, width=34)
        self.q33.configure(activebackground="#f9f9f9")
        self.q33.configure(activeforeground="black")
        self.q33.configure(background="#d9d9d9")
        self.q33.configure(disabledforeground="#a3a3a3")
        self.q33.configure(foreground="#000000")
        self.q33.configure(highlightbackground="#d9d9d9")
        self.q33.configure(highlightcolor="black")

        self.q32 = tk.Label(top)
        self.q32.place(relx=0.483, rely=0.397, height=21, width=34)
        self.q32.configure(activebackground="#f9f9f9")
        self.q32.configure(activeforeground="black")
        self.q32.configure(background="#d9d9d9")
        self.q32.configure(disabledforeground="#a3a3a3")
        self.q32.configure(foreground="#000000")
        self.q32.configure(highlightbackground="#d9d9d9")
        self.q32.configure(highlightcolor="black")

        self.q31 = tk.Label(top)
        self.q31.place(relx=0.564, rely=0.397, height=21, width=36)
        self.q31.configure(activebackground="#f9f9f9")
        self.q31.configure(activeforeground="black")
        self.q31.configure(background="#d9d9d9")
        self.q31.configure(disabledforeground="#a3a3a3")
        self.q31.configure(foreground="#000000")
        self.q31.configure(highlightbackground="#d9d9d9")
        self.q31.configure(highlightcolor="black")

        self.q41 = tk.Label(top)
        self.q41.place(relx=0.564, rely=0.468, height=21, width=36)
        self.q41.configure(activebackground="#f9f9f9")
        self.q41.configure(activeforeground="black")
        self.q41.configure(background="#d9d9d9")
        self.q41.configure(disabledforeground="#a3a3a3")
        self.q41.configure(foreground="#000000")
        self.q41.configure(highlightbackground="#d9d9d9")
        self.q41.configure(highlightcolor="black")

        self.q42 = tk.Label(top)
        self.q42.place(relx=0.483, rely=0.468, height=21, width=34)
        self.q42.configure(activebackground="#f9f9f9")
        self.q42.configure(activeforeground="black")
        self.q42.configure(background="#d9d9d9")
        self.q42.configure(disabledforeground="#a3a3a3")
        self.q42.configure(foreground="#000000")
        self.q42.configure(highlightbackground="#d9d9d9")
        self.q42.configure(highlightcolor="black")

        self.q43 = tk.Label(top)
        self.q43.place(relx=0.41, rely=0.468, height=21, width=34)
        self.q43.configure(activebackground="#f9f9f9")
        self.q43.configure(activeforeground="black")
        self.q43.configure(background="#d9d9d9")
        self.q43.configure(disabledforeground="#a3a3a3")
        self.q43.configure(foreground="#000000")
        self.q43.configure(highlightbackground="#d9d9d9")
        self.q43.configure(highlightcolor="black")

        self.q61 = tk.Label(top)
        self.q61.place(relx=0.564, rely=0.61, height=21, width=36)
        self.q61.configure(activebackground="#f9f9f9")
        self.q61.configure(activeforeground="black")
        self.q61.configure(background="#d9d9d9")
        self.q61.configure(disabledforeground="#a3a3a3")
        self.q61.configure(foreground="#000000")
        self.q61.configure(highlightbackground="#d9d9d9")
        self.q61.configure(highlightcolor="black")

        self.q62 = tk.Label(top)
        self.q62.place(relx=0.483, rely=0.61, height=21, width=34)
        self.q62.configure(activebackground="#f9f9f9")
        self.q62.configure(activeforeground="black")
        self.q62.configure(background="#d9d9d9")
        self.q62.configure(disabledforeground="#a3a3a3")
        self.q62.configure(foreground="#000000")
        self.q62.configure(highlightbackground="#d9d9d9")
        self.q62.configure(highlightcolor="black")

        self.q63 = tk.Label(top)
        self.q63.place(relx=0.41, rely=0.61, height=21, width=34)
        self.q63.configure(activebackground="#f9f9f9")
        self.q63.configure(activeforeground="black")
        self.q63.configure(background="#d9d9d9")
        self.q63.configure(cursor="fleur")
        self.q63.configure(disabledforeground="#a3a3a3")
        self.q63.configure(foreground="#000000")
        self.q63.configure(highlightbackground="#d9d9d9")
        self.q63.configure(highlightcolor="black")

        self.q71 = tk.Label(top)
        self.q71.place(relx=0.564, rely=0.681, height=21, width=36)
        self.q71.configure(activebackground="#f9f9f9")
        self.q71.configure(activeforeground="black")
        self.q71.configure(background="#d9d9d9")
        self.q71.configure(disabledforeground="#a3a3a3")
        self.q71.configure(foreground="#000000")
        self.q71.configure(highlightbackground="#d9d9d9")
        self.q71.configure(highlightcolor="black")

        self.q72 = tk.Label(top)
        self.q72.place(relx=0.483, rely=0.681, height=21, width=34)
        self.q72.configure(activebackground="#f9f9f9")
        self.q72.configure(activeforeground="black")
        self.q72.configure(background="#d9d9d9")
        self.q72.configure(disabledforeground="#a3a3a3")
        self.q72.configure(foreground="#000000")
        self.q72.configure(highlightbackground="#d9d9d9")
        self.q72.configure(highlightcolor="black")

        self.q73 = tk.Label(top)
        self.q73.place(relx=0.41, rely=0.681, height=21, width=34)
        self.q73.configure(activebackground="#f9f9f9")
        self.q73.configure(activeforeground="black")
        self.q73.configure(background="#d9d9d9")
        self.q73.configure(disabledforeground="#a3a3a3")
        self.q73.configure(foreground="#000000")
        self.q73.configure(highlightbackground="#d9d9d9")
        self.q73.configure(highlightcolor="black")

        self.q83 = tk.Label(top)
        self.q83.place(relx=0.41, rely=0.738, height=21, width=34)
        self.q83.configure(activebackground="#f9f9f9")
        self.q83.configure(activeforeground="black")
        self.q83.configure(background="#d9d9d9")
        self.q83.configure(disabledforeground="#a3a3a3")
        self.q83.configure(foreground="#000000")
        self.q83.configure(highlightbackground="#d9d9d9")
        self.q83.configure(highlightcolor="black")

        self.q82 = tk.Label(top)
        self.q82.place(relx=0.483, rely=0.738, height=21, width=34)
        self.q82.configure(activebackground="#f9f9f9")
        self.q82.configure(activeforeground="black")
        self.q82.configure(background="#d9d9d9")
        self.q82.configure(disabledforeground="#a3a3a3")
        self.q82.configure(foreground="#000000")
        self.q82.configure(highlightbackground="#d9d9d9")
        self.q82.configure(highlightcolor="black")

        self.q81 = tk.Label(top)
        self.q81.place(relx=0.564, rely=0.738, height=21, width=36)
        self.q81.configure(activebackground="#f9f9f9")
        self.q81.configure(activeforeground="black")
        self.q81.configure(background="#d9d9d9")
        self.q81.configure(disabledforeground="#a3a3a3")
        self.q81.configure(foreground="#000000")
        self.q81.configure(highlightbackground="#d9d9d9")
        self.q81.configure(highlightcolor="black")

        self.q51 = tk.Label(top)
        self.q51.place(relx=0.564, rely=0.553, height=21, width=35)
        self.q51.configure(background="#d9d9d9")
        self.q51.configure(disabledforeground="#a3a3a3")
        self.q51.configure(foreground="#000000")

        self.q52 = tk.Label(top)
        self.q52.place(relx=0.483, rely=0.553, height=21, width=34)
        self.q52.configure(background="#d9d9d9")
        self.q52.configure(disabledforeground="#a3a3a3")
        self.q52.configure(foreground="#000000")

        self.q53 = tk.Label(top)
        self.q53.place(relx=0.41, rely=0.553, height=21, width=34)
        self.q53.configure(background="#d9d9d9")
        self.q53.configure(disabledforeground="#a3a3a3")
        self.q53.configure(foreground="#000000")
        self.SekerOutcomes()

if __name__ == '__main__':
    vp_start_gui()





