#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.0
#  in conjunction with Tcl version 8.6
<<<<<<< HEAD:infastructure/TransWorkClock_support.py
#    Jan 03, 2021 04:10:45 PM +0200  platform: Windows NT
=======

#    Dec 27, 2020 06:43:25 PM +0200  platform: Windows NT
#    Dec 31, 2020 11:27:36 AM +0200  platform: Windows NT
#    Dec 27, 2020 06:43:25 PM +0200  platform: Windows NT
#    Dec 31, 2020 11:27:36 AM +0200  platform: Windows NT

>>>>>>> 880b965bcf2f9e78016aa3eee89c113c6bcd346e:infastructure/GamesStudent_support.py

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import TransWorkClock
    TransWorkClock.vp_start_gui()




