#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0
#  in conjunction with Tcl version 8.6
#    Dec 28, 2020 08:25:39 PM +0200  platform: Windows NT

import sys
import pymongo

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import datetime
import TuitionStudent_support
import Studentmainmenu
from tkinter import messagebox
sys.path.append('..')

from data import user_db_init
user_db_init()
client = pymongo.MongoClient()
mydb = client['EZSchooldb']
userobj=None

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Tuition (root)
    TuitionStudent_support.init(root, top)
    root.mainloop()

w = None
def create_Tuition(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Tuition(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Tuition (w)
    TuitionStudent_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Tuition():
    global w
    w.destroy()
    w = None

class Tuition:
    def back(self):
        root.destroy()
        Studentmainmenu.vp_start_gui()
    def txt(self):
        f = open("Current_user.txt")
        id=f.readline()
        id=id[:9]
        global userobj
        global mydb
        userobj = mydb['Users'].find_one({'id': id})
        key="Tuition"+userobj["id"]
        return (userobj['name']+"\n"+userobj['id']+"\nיתרה:"+str(userobj[key]))

    def submit(self):
        global userobj
        key="Tuition"+userobj["id"]
        year=int(self.year_entry.get())
        month=int(self.month_entry.get())
        idofcard=self.id_entry.get()
        cardnumber=self.card_entry.get()
        amount=self.amount_entry.get()
        balance=userobj[key]
        flag=1
        for c in amount:
            if c < '0' or c > '9':
                flag = 0
                tk.messagebox.showwarning('Tuition', 'סכום לא תקין- חייב להכיל ספרות בלבד')
        if flag:
            amount=float(amount)
            if (amount <= 0 or amount == None):
                tk.messagebox.showwarning('Tuition', 'סכום לא תקין-חייב להיות חיובי, נסה שוב')
                flag = 0
        if flag:
            if(len(cardnumber)<16):
                tk.messagebox.showwarning('Tuition', 'מספר הכרטיס אינו תקין-קצר מידי, נסה שוב')
                flag=0
        if flag:
            for c in cardnumber:
                if c<'0'or c>'9':
                    flag=0
                    tk.messagebox.showwarning('Tuition', 'מספר הכרטיס אינו תקין-חייב להכיל ספרות בלבד, נסה שוב')

        if flag:
            if len(idofcard) != 9:
                tk.messagebox.showwarning('Tuition', 'מספר תעודת הזהות אינו תקין-אורכו צריך להיות 9 ספרות, נסה שוב')
                flag = 0
        if flag:
            for c in idofcard:
                if c < '0' or c > '9':
                    flag = 0
                    tk.messagebox.showwarning('Tuition', 'מספר תעודת הזהות אינו תקין-חייב להכיל ספרות בלבד, נסה שוב')

        today=datetime.datetime.today()
        yeartoday=today.year
        monthtoday=today.month
        if flag:
            if month <1 or month>12:
                print(month)
                tk.messagebox.showwarning('Tuition', 'תאריך לא תקין')
                flag = 0

        if flag:
            if year<yeartoday:
                tk.messagebox.showwarning('Tuition', 'תאריך לא תקין, נסה שוב')
                flag = 0
            elif year==yeartoday:
                if month<monthtoday:
                    tk.messagebox.showwarning('Tuition', 'תאריך לא תקין')
                    flag = 0


        if flag:
            myquery={key:userobj[key]}
            mycol=mydb['Users']
            newval={"$set":{key:balance+amount}}
            mycol.update_one(myquery,newval)
            tk.messagebox._show('Tuition', 'התשלום התקבל בהצלחה')
            self.back()



    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+468+138")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("תשלום שכר לימוד")
        top.configure(background="#c9e9e8")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.mainmenu = tk.Button(top)
        self.mainmenu.place(relx=0.05, rely=0.844, height=44, width=147)
        self.mainmenu.configure(activebackground="#ececec")
        self.mainmenu.configure(activeforeground="#000000")
        self.mainmenu.configure(background="#8fd1cf")
        self.mainmenu.configure(disabledforeground="#a3a3a3")
        self.mainmenu.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.mainmenu.configure(foreground="#000000")
        self.mainmenu.configure(highlightbackground="#d9d9d9")
        self.mainmenu.configure(highlightcolor="black")
        self.mainmenu.configure(pady="0")
        self.mainmenu.configure(text='''תפריט ראשי''')
        self.mainmenu.configure(command= self.back)



        self.submitpayment = tk.Button(top)
        self.submitpayment.place(relx=0.35, rely=0.844, height=44, width=137)
        self.submitpayment.configure(activebackground="#ececec")
        self.submitpayment.configure(activeforeground="#000000")
        self.submitpayment.configure(background="#8fd1cf")
        self.submitpayment.configure(disabledforeground="#a3a3a3")
        self.submitpayment.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.submitpayment.configure(foreground="#000000")
        self.submitpayment.configure(highlightbackground="#d9d9d9")
        self.submitpayment.configure(highlightcolor="black")
        self.submitpayment.configure(pady="0")
        self.submitpayment.configure(text='''תשלום''')
        self.submitpayment.configure(command=self.submit)

        self.amount_entry = tk.Entry(top)
        self.amount_entry.place(relx=0.45, rely=0.222, height=20, relwidth=0.173)

        self.amount_entry.configure(background="white")
        self.amount_entry.configure(disabledforeground="#a3a3a3")
        self.amount_entry.configure(font="TkFixedFont")
        self.amount_entry.configure(foreground="#000000")
        self.amount_entry.configure(insertbackground="black")

        self.card_entry = tk.Entry(top)
        self.card_entry.place(relx=0.3, rely=0.311, height=20, relwidth=0.323)
        self.card_entry.configure(background="white")
        self.card_entry.configure(disabledforeground="#a3a3a3")
        self.card_entry.configure(font="TkFixedFont")
        self.card_entry.configure(foreground="#000000")
        self.card_entry.configure(insertbackground="black")

        self.id_entry = tk.Entry(top)
        self.id_entry.place(relx=0.433, rely=0.4, height=20, relwidth=0.19)
        self.id_entry.configure(background="white")
        self.id_entry.configure(disabledforeground="#a3a3a3")
        self.id_entry.configure(font="TkFixedFont")
        self.id_entry.configure(foreground="#000000")
        self.id_entry.configure(insertbackground="black")

        self.userDetails = tk.Message(top)
        self.userDetails.place(relx=0.233, rely=0.022, relheight=0.118
                , relwidth=0.617)
        self.userDetails.configure(background="#c9e9e8")
        self.userDetails.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.userDetails.configure(foreground="#000000")
        self.userDetails.configure(highlightbackground="#d9d9d9")
        self.userDetails.configure(highlightcolor="black")
        self.userDetails.configure(text=self.txt())
        self.userDetails.configure(width=370)

        self.amount = tk.Message(top)
        self.amount.place(relx=0.633, rely=0.222, relheight=0.051 , relwidth=0.233)
        self.amount.configure(background="#c9e9e8")
        self.amount.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.amount.configure(foreground="#000000")
        self.amount.configure(highlightbackground="#d9d9d9")
        self.amount.configure(highlightcolor="black")
        self.amount.configure(text='''סכום לתשלום''')
        self.amount.configure(width=140)

        self.card = tk.Message(top)
        self.card.place(relx=0.65, rely=0.311, relheight=0.051, relwidth=0.217)
        self.card.configure(background="#c9e9e8")
        self.card.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.card.configure(foreground="#000000")
        self.card.configure(highlightbackground="#d9d9d9")
        self.card.configure(highlightcolor="black")
        self.card.configure(text='''מספר כרטיס''')
        self.card.configure(width=130)

        self.id = tk.Message(top)
        self.id.place(relx=0.683, rely=0.4, relheight=0.051, relwidth=0.25)
        self.id.configure(background="#c9e9e8")
        self.id.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.id.configure(foreground="#000000")
        self.id.configure(highlightbackground="#d9d9d9")
        self.id.configure(highlightcolor="black")
        self.id.configure(text='''תעודת זהות של בעל כרטיס''')
        self.id.configure(width=150)

        self.year = tk.Message(top)
        self.year.place(relx=0.617, rely=0.489, relheight=0.051, relwidth=0.233)
        self.year.configure(background="#c9e9e8")
        self.year.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.year.configure(foreground="#000000")
        self.year.configure(highlightbackground="#d9d9d9")
        self.year.configure(highlightcolor="black")
        self.year.configure(text='''שנה''')
        self.year.configure(width=140)

        self.month = tk.Message(top)
        self.month.place(relx=0.683, rely=0.578, relheight=0.051, relwidth=0.1)
        self.month.configure(background="#c9e9e8")
        self.month.configure(cursor="fleur")
        self.month.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.month.configure(foreground="#000000")
        self.month.configure(highlightbackground="#d9d9d9")
        self.month.configure(highlightcolor="black")
        self.month.configure(text='''חודש''')
        self.month.configure(width=60)

        self.year_entry = tk.Entry(top)
        self.year_entry.place(relx=0.483, rely=0.489, height=20, relwidth=0.14)
        self.year_entry.configure(background="white")
        self.year_entry.configure(disabledforeground="#a3a3a3")
        self.year_entry.configure(font="TkFixedFont")
        self.year_entry.configure(foreground="#000000")
        self.year_entry.configure(insertbackground="black")

        self.month_entry = tk.Entry(top)
        self.month_entry.place(relx=0.5, rely=0.578, height=20, relwidth=0.123)
        self.month_entry.configure(background="white")
        self.month_entry.configure(disabledforeground="#a3a3a3")
        self.month_entry.configure(font="TkFixedFont")
        self.month_entry.configure(foreground="#000000")
        self.month_entry.configure(insertbackground="black")


if __name__ == '__main__':
    vp_start_gui()





