#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0
#  in conjunction with Tcl version 8.6
#    Jan 05, 2021 05:46:27 PM +0200  platform: Windows NT

import sys
sys.path.append('..')
from tkcalendar import *
import pymongo
import datetime
from tkinter import filedialog
from data import getUser, connect_to_db_and_collection, connect_to_db
import base64
import gridfs


try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import UploadAssTeacher_support
import Teachermainmenu

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = UploadAssTeacher (root)
    UploadAssTeacher_support.init(root, top)
    root.mainloop()

w = None
def create_UploadAssTeacher(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_UploadAssTeacher(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = UploadAssTeacher (w)
    UploadAssTeacher_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_UploadAssTeacher():
    global w
    w.destroy()
    w = None

class UploadAssTeacher:
    def openMainmenue(self):
        root.destroy()
        Teachermainmenu.vp_start_gui()

    def chooseFile(self):
        self.newfile = filedialog.askopenfile(initialdir='/', title="תבחר קובץ להעלאה", mode='rb',
            filetypes=[('PDF files', '*pdf'), ('RAR files', '*.rar'), ('ZIP files', '*zip')])

    def UploadFile(self):
        assigment_date = self.uploadCalendar.get_date()
        db = connect_to_db('EZSchooldb')
        collection = connect_to_db_and_collection('EZSchooldb','MathAssignments')
        encoded_string = base64.b64encode(self.newfile.read())
        # fs = gridfs.GridFS(db)     # בבדיקה
        #with fs.new_file( chunkSize=800000, filename='Assigment') as fp:
        #    fp.write(encoded_string)
        assign_num = int(self.UplSpnBX.get())
        data = {'due_in': assigment_date,'Assigment_file': encoded_string, 'Assigment_num': assign_num}
        flag=0
        for assign in collection.find({}):
            if assign['Assigment_num'] == assign_num:
                flag =1
                break;
        if flag == 1:
            collection.delete_one({'Assigment_num': assign_num})
        collection.insert_one(data)
        root.destroy()
        Teachermainmenu.vp_start_gui()


    def __init__(self, top=None):
        self.current_user = getUser()
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("679x496+582+295")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("העלאת מטלות")
        top.configure(background="#80ffff")

        self.MainMenuBtn = tk.Button(top)
        self.MainMenuBtn.place(relx=0.032, rely=0.823, height=64, width=127)
        self.MainMenuBtn.configure(activebackground="#ececec")
        self.MainMenuBtn.configure(activeforeground="#000000")
        self.MainMenuBtn.configure(background="#ffffff")
        self.MainMenuBtn.configure(disabledforeground="#a3a3a3")
        self.MainMenuBtn.configure(font="-family {Segoe UI} -size 14 -weight bold")
        self.MainMenuBtn.configure(foreground="#000000")
        self.MainMenuBtn.configure(highlightbackground="#d9d9d9")
        self.MainMenuBtn.configure(highlightcolor="black")
        self.MainMenuBtn.configure(pady="0")
        self.MainMenuBtn.configure(text='''תפריט ראשי''')
        self.MainMenuBtn.configure(command=self.openMainmenue)

        self.DueDateL = tk.Label(top)
        self.DueDateL.place(relx=0.060, rely=0.04, height=41, width=214)
        self.DueDateL.configure(background="#00ff40")
        self.DueDateL.configure(disabledforeground="#a3a3a3")
        self.DueDateL.configure(font="-family {Segoe UI} -size 14 -weight bold")
        self.DueDateL.configure(foreground="#000000")
        self.DueDateL.configure(relief="ridge")
        self.DueDateL.configure(text='''לבחירת תאריך הגשה''')

        self.UploadBtn = tk.Button(top)
        self.UploadBtn.place(relx=0.324, rely=0.645, height=64, width=237)
        self.UploadBtn.configure(activebackground="#ececec")
        self.UploadBtn.configure(activeforeground="#000000")
        self.UploadBtn.configure(background="#ff0000")
        self.UploadBtn.configure(disabledforeground="#a3a3a3")
        self.UploadBtn.configure(font="-family {Segoe UI} -size 12 -weight bold -underline 1")
        self.UploadBtn.configure(foreground="#000000")
        self.UploadBtn.configure(highlightbackground="#d9d9d9")
        self.UploadBtn.configure(highlightcolor="black")
        self.UploadBtn.configure(pady="0")
        self.UploadBtn.configure(text='''להעלאה לחץ כאן''')
        self.UploadBtn.configure(command=self.UploadFile)

        self.FileChoiceBtn = tk.Button(top)
        self.FileChoiceBtn.place(relx=0.56, rely=0.242, height=74, width=227)
        self.FileChoiceBtn.configure(activebackground="#ececec")
        self.FileChoiceBtn.configure(activeforeground="#000000")
        self.FileChoiceBtn.configure(background="#ff8000")
        self.FileChoiceBtn.configure(disabledforeground="#a3a3a3")
        self.FileChoiceBtn.configure(font="-family {Segoe UI} -size 14 -weight bold")
        self.FileChoiceBtn.configure(foreground="#000000")
        self.FileChoiceBtn.configure(highlightbackground="#d9d9d9")
        self.FileChoiceBtn.configure(highlightcolor="black")
        self.FileChoiceBtn.configure(pady="0")
        self.FileChoiceBtn.configure(text='''לבחירת הקובץ''')
        self.FileChoiceBtn.configure(command=self.chooseFile)

        self.date = datetime.datetime.now()
        self.uploadCalendar = Calendar(top, selectmode='day',year=self.date.year,
                                       month=self.date.month, day=self.date.day)
        self.uploadCalendar.place(relx=0.030, rely=0.15, height=220, width=250)

        self.UplSpnBX = tk.Spinbox(top, from_=1.0, to=100.0)
        self.UplSpnBX.place(relx=0.62, rely=0.54, relheight=0.042
                            , relwidth=0.225)
        self.UplSpnBX.configure(activebackground="#f9f9f9")
        self.UplSpnBX.configure(background="white")
        self.UplSpnBX.configure(buttonbackground="#d9d9d9")
        self.UplSpnBX.configure(disabledforeground="#a3a3a3")
        self.UplSpnBX.configure(font="TkDefaultFont")
        self.UplSpnBX.configure(foreground="black")
        self.UplSpnBX.configure(highlightbackground="black")
        self.UplSpnBX.configure(highlightcolor="black")
        self.UplSpnBX.configure(insertbackground="black")
        self.UplSpnBX.configure(justify='center')
        self.UplSpnBX.configure(selectbackground="blue")
        self.UplSpnBX.configure(selectforeground="white")
        self.UplSpnBX.configure(value=list(range(1, connect_to_db_and_collection('EZSchooldb', 'MathAssignments').estimated_document_count() + 2)))

        self.UplAssL = tk.Label(top)
        self.UplAssL.place(relx=0.58, rely=0.47, relheight=0.042
                            , relwidth=0.3)
        self.UplAssL.configure(background="#00ff80")
        self.UplAssL.configure(disabledforeground="#a3a3a3")
        self.UplAssL.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.UplAssL.configure(foreground="#000000")
        self.UplAssL.configure(relief="ridge")
        self.UplAssL.configure(text='''לבחירת מס' מטלה להעלאה''')

        self.titleL = tk.Label(top)
        self.titleL.place(relx=0.6, rely=0.04, relheight=0.1, relwidth=0.244)
        self.titleL.configure(background="#0080ff")
        self.titleL.configure(disabledforeground="#a3a3a3")
        self.titleL.configure(font="-family {Segoe UI} -size 14 -weight bold -underline 1")
        self.titleL.configure(foreground="#000000")
        self.titleL.configure(relief="ridge")
        self.titleL.configure(text='''חשבון''')



if __name__ == '__main__':
    vp_start_gui()





