#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0
#  in conjunction with Tcl version 8.6
#    Jan 03, 2021 04:07:48 PM +0200  platform: Windows NT

import sys
import pymongo
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
sys.path.append('..')
from data import user_db_init
user_db_init()
client = pymongo.MongoClient()
mydb = client['EZSchooldb']
import WorkClock_support
from datetime import datetime
import WorkClock
import ClockReport
import TransWorkClock

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    WorkClock_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    WorkClock_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def Enter(self):
        f = open("Current_user.txt")
        id = f.readline()
        id = id[:9]
        name="work"+" "+id+".txt"
        f.close()
        date= datetime.now()
        if date.day==1:
            userobj = mydb['Users'].find_one({'id': id})
            mydb['Users'].update_one({'id': id}, {'$set': {'workhours': 0}})
            f = open(name, "w")
        else:
            f=open(name,"a")
        date = str(date)
        date = date[0:16:]
        f.write(date)
        f.close()
        root.destroy()
    def Exit(self):
        f = open("Current_user.txt")
        id = f.readline()
        id = id[:9]
        name="work"+" "+id+".txt"
        f.close()
        f=open(name,"r")
        inhours=f.read()
        f.close()
        f = open(name, "a")
        hours=int(inhours[-5:-3])
        min=int(inhours[-2:])
        date =datetime.now()
        res= date.hour-hours +((date.minute-min)/60)
        date=str(date)
        date = date[0:16:]
        date=date[-5:]
        f.write("   "+date+"    "+str(res)[:5]+"\n")
        f.close()
        userobj = mydb['Users'].find_one({'id': id})
        mydb['Users'].update_one({'id':id},{'$set':{'workhours':userobj['workhours']+res}})
        root.destroy()

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("305x144+723+230")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("שעון נוכחות")
        top.configure(background="#ffff80")

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.131, rely=0.417, height=44, width=97)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''יציאה''')
        self.Button1.configure(command=self.Exit)

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.557, rely=0.417, height=44, width=97)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''כניסה''')
        self.Button2.configure(command=self.Enter)

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.197, rely=0.139, height=21, width=184)
        self.Label1.configure(background="#ffff80")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 12 -weight bold")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''אנא בחר את פעולתך''')

if __name__ == '__main__':
    vp_start_gui()





